### ISSUE TITLE
CLI binary should be a separate crate

### ISSUE THREAD

**Issue by Speykious** [limikael/appy#1]
The `appy` binary, which is currently written in `src/cl/bin.rs`, should be its own separate crate.

That way, the dependencies of the library and those of the binary can be completely separated out, so if someone uses the Appy library in their project, they'll only need to compile these dependencies.

**Comment by limikael** [comment]
Yes, keeping them separate would be nice! The only drawback would be that if I publish this on crates.io, then the library and the binary would have to be published as two separate crates. Am I right? If so, is there perhaps some other way to separate the dependencies for the library and the binary?

I'm also open to creating two separate crates. It might also be an advantage actually, since then people could use the packager for any SDL project, not just appy projects.

But would like to ask you first, is it possible to keep them in the same crate on crates.io, even though they are separate crates in the project?

**Comment by Speykious** [comment]
It's not possible to publish them under the same crate, no. In fact, it would kinda defeat the entire point of separating dependencies, since when downloading the crate, you would have to download the binary as well... xD

However, it's quite common practice to publish a crate under `name` and then the one related executable under `name-cli`. For example, the [`sqlx`](https://crates.io/crates/sqlx) crate provides an [`sqlx-cli`](https://crates.io/crates/sqlx-cli) binary for various stuff like database migrations.

An alternative naming solution would be to name it `cargo-appy`, since it's installable through `cargo install`, similar to tools like [cargo-bloat](https://github.com/RazrFalcon/cargo-bloat).

Once the crate is made, we'd just have to run the command `cargo install --path cargo-appy`, or `cargo install --git https://github.com/limikael/appy cargo-appy` (I'm unsure if the latter works).

You'll then need a root-level `Cargo.toml` to describe a cargo workspace containing the two crates `appy` and `appy-cli` (basically 2 small lines of config).

**Comment by limikael** [comment]
Ok! I think it might actually best then to separate it out to a separate repository, since there is noting really appy specific about it. It does a very similar thing to [cargo-apk](https://crates.io/crates/cargo-apk). cargo-apk can not be used to build SDL apps, however, because SDL has its own java stub. So the tool does the same thing as cargo-apk, but using SDL's java stub, so it would make sense to call it cargo-sdl-apk. I asked on the SDL forum what they think about the idea:

https://discourse.libsdl.org/t/android-build-tool-for-rust/43437

What do you think?

**Comment by Speykious** [comment]
Oh, so that's all the `appy-cli` does? Ok then, yeah it's a good idea since it'll be useful to other people who have projects using SDL.

**Comment by limikael** [comment]
After having given this some though and done some more research I'm thinking to switch to glutin for the window management. This way we can use [cargo-apk](https://crates.io/crates/cargo-apk) instead. Better to not reinvent the wheel... So will close the issue and start working on a new branch.

**Comment by Speykious** [comment]
How about [miniquad](https://github.com/not-fl3/miniquad)?

It has very minimal dependencies, compiles under two seconds, supports Android really easily (with [cargo-quad-apk](https://github.com/not-fl3/cargo-quad-apk) and probably the same for iOS, and plans to support Metal rendering too.

**Comment by limikael** [comment]
Ah miniquad looks really cool! I love the minimalism... 

I think I will support different backends, and make it possible to select via features... So sdl, glutin and miniquad... 

Will leave the issue open until I have something to show...

**Comment by limikael** [comment]
There is now:

https://github.com/limikael/cargo-sdl-apk

And started some work to make it "multi-backend" on this branch:

https://github.com/limikael/appy/tree/glutin

**Comment by limikael** [comment]
Alright, I think I have it working now... And I updated the README file with instructions on how to get started...

So the matrix with supported platforms and libraries is now:

* SDL for desktop
* SDL for Android
* Glutin for desktop
* Glutin for Android

Would be interested to know how many of these four you can get up and running? And, any feedback on the README? Something I should mention there in order to increase the chances of getting more people to tryit?

**Comment by limikael** [comment]
Anyway, as the issue was reported, I think we can consider it resolved... So closing... But still interested in weather you can get it to run or not..

**Comment by Speykious** [comment]
Sorry for not responding earlier! I was getting myself busy with a recent project of mine... ^^'

I might try all of this today, at least for Desktop (since my Android setup never seems to be correct for some reason).

Although I encourage anyone else reading this to test it :)

**Comment by Speykious** [comment]
Better late than never...
I tried all examples on Desktop and they work flawlessly on my Linux machine. I'd say this is a win!

**Comment by limikael** [comment]
Awesome! Thank you so much for feedback testing and contributions!!! Btw... Do you hang out on some discord server or so?

**Comment by Speykious** [comment]
Oh yeah, I do. Feel free to add me, I'm **Speykious#7435**
