### ISSUE TITLE
Add LICENSE file(s)

### ISSUE THREAD

**Issue by rtkay123** [limikael/appy#3]

**Comment by limikael** [comment]
Alright I added it. Without understanding fully what I'm doing, I chose the GLP-3.0 license. Is this a good license or another license preferable for potential users?

**Comment by limikael** [comment]
Awaiting you comment before I close the issue...

**Comment by rtkay123** [comment]
The most used in the community is MIT (sometimes dual licensing MIT + Apache 2.0). The GPL could be restrictive in some cases, I believe (I could be wrong) GPL requires potential users to make their source code open. Which of course, may be a deal breaker in some cases.

**Comment by Speykious** [comment]
GPL is *extremely* restrictive. It is good for some open-source projects, especially big applications like GIMP or OBS, but for a GUI library, I think it's better if it has a permissive open-source license that blends in well with the rest of the Rust ecosystem.
Almost the entire Rust ecosystem is made of crates licensed under dual licensing MIT + Apache 2.0, so that would be the ideal choice.

**Comment by rtkay123** [comment]
> for a GUI library, I think it's better if it has a permissive open-source license that blends in well with the rest of the Rust ecosystem

Yeah, that sounds great

**Comment by limikael** [comment]
Ok, changed to MIT license.
